# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/AES/AES.srcs/sources_1/bd/aes_bd/ip/aes_bd_aes_encrypt_top_0_0/aes_bd_aes_encrypt_top_0_0.xci
# IP: The module: 'aes_bd_aes_encrypt_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/AES/AES.srcs/sources_1/bd/aes_bd/ip/aes_bd_aes_encrypt_top_0_0/constraints/aes_encrypt_top_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'aes_bd_aes_encrypt_top_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/AES/AES.srcs/sources_1/bd/aes_bd/ip/aes_bd_aes_encrypt_top_0_0/aes_bd_aes_encrypt_top_0_0.xci
# IP: The module: 'aes_bd_aes_encrypt_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/AES/AES.srcs/sources_1/bd/aes_bd/ip/aes_bd_aes_encrypt_top_0_0/constraints/aes_encrypt_top_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'aes_bd_aes_encrypt_top_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
