# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/aes_bd/aes_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aes_bd || ORIG_REF_NAME==aes_bd} -quiet] -quiet

# IP: bd/aes_bd/ip/aes_bd_processing_system7_0_0/aes_bd_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aes_bd_processing_system7_0_0 || ORIG_REF_NAME==aes_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/aes_bd/ip/aes_bd_axi_dma_0_0/aes_bd_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aes_bd_axi_dma_0_0 || ORIG_REF_NAME==aes_bd_axi_dma_0_0} -quiet] -quiet

# IP: bd/aes_bd/ip/aes_bd_axi_smc_0/aes_bd_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aes_bd_axi_smc_0 || ORIG_REF_NAME==aes_bd_axi_smc_0} -quiet] -quiet

# IP: bd/aes_bd/ip/aes_bd_rst_ps7_0_100M_0/aes_bd_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aes_bd_rst_ps7_0_100M_0 || ORIG_REF_NAME==aes_bd_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/aes_bd/ip/aes_bd_xbar_0/aes_bd_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aes_bd_xbar_0 || ORIG_REF_NAME==aes_bd_xbar_0} -quiet] -quiet

# IP: bd/aes_bd/ip/aes_bd_auto_pc_0/aes_bd_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aes_bd_auto_pc_0 || ORIG_REF_NAME==aes_bd_auto_pc_0} -quiet] -quiet

# IP: bd/aes_bd/ip/aes_bd_ps7_0_axi_periph_0/aes_bd_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aes_bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==aes_bd_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/aes_bd/ip/aes_bd_aes_encrypt_top_0_0/aes_bd_aes_encrypt_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aes_bd_aes_encrypt_top_0_0 || ORIG_REF_NAME==aes_bd_aes_encrypt_top_0_0} -quiet] -quiet

# IP: bd/aes_bd/ip/aes_bd_xlconcat_0_0/aes_bd_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aes_bd_xlconcat_0_0 || ORIG_REF_NAME==aes_bd_xlconcat_0_0} -quiet] -quiet

# XDC: bd/aes_bd/aes_bd_ooc.xdc
